name: Security Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slither:
    name: Security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - Slither For HardHat

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true
        id: slither
        with:
          node-version: 16
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
          github_token: ${{ github.token }}
