name: Security Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slither:
    name: Security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - Slither For HardHat

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip

      - name: Install slither
        run: |
          pip3 install slither-analyzer

      - name: Run slither
        run: slither .
